### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by baggepinnen** [org-arl/InteractiveViz.jl#1]
Some keyboard shortcuts are not working for me, the ones not working are
- `-`
- `[ ]`

I have a Scandinavian keyboard which might be part of the problem

**Comment by mchitre** [comment]
Hmm. Will figure out a nice way to let user customize keys.

**Comment by mchitre** [comment]
I've added a way to customize the key bindings. See if this solves it for you.
```julia
using InteractiveViz, Makie
InteractiveViz.keymap[:zoom_y_out] = Keyboard._1    # now use "1" to zoom out instead of "-"
```
Once this is done, new plots will use this binding.

Default bindings:
```
  :pan_left => Keyboard.left,
  :pan_right => Keyboard.right,
  :pan_up => Keyboard.up,
  :pan_down => Keyboard.down,
  :zoom_x_out => Keyboard.left_bracket,
  :zoom_x_in => Keyboard.right_bracket,
  :zoom_y_out => Keyboard.minus,
  :zoom_y_in => Keyboard.equal,
  :brightness_down => Keyboard.comma,
  :brightness_up => Keyboard.period,
  :contrast_up => Keyboard.semicolon,
  :contrast_down => Keyboard.apostrophe,
  :reset => Keyboard._0
```

**Comment by baggepinnen** [comment]
This package does not declare compatibility with latest Makie v0.11 and the older Makie does not build on my system (the newer one does).

**Comment by mchitre** [comment]
I can update the compat after testing it, but perhaps you can try against the referenced commit above (https://github.com/org-arl/InteractiveViz.jl/commit/c3f1c770f0ca00a6415e3909093dc857471267d3), which is before the compat section was added?

**Comment by baggepinnen** [comment]
Yep, 
```julia
InteractiveViz.keymap[:zoom_y_out] = Keyboard._1
InteractiveViz.keymap[:zoom_y_in]  = Keyboard._2
```
works very well :)

**Comment by baggepinnen** [comment]
I had a look at the code but couldn't figure out if this would be simple to add, but Plotly resets the plot to the initial view if you double click on it, quite handy feature if you're zooming in with the mouse.

**Comment by mchitre** [comment]
Shouldn't be hard to do ... will try to include it in v0.1.1 shortly after the v0.1.0 release is out after the mandatory waiting time.

**Comment by mchitre** [comment]
Tracked suggestion as #2, so closing this.
