### ISSUE TITLE
Support for Multiple Windows

### ISSUE THREAD

**Issue by tkgunaratne** [org-arl/InteractiveViz.jl#19]
This seems to be a great Julia package for plotting large number of points really fast. I've noticed that GLMakie allow multiple plot windows. I wonder InteractiveViz.jl too support this?

**Comment by mchitre** [comment]
I haven't looked at multiple windows support in GLMakie. Will take a look.

**Comment by mchitre** [comment]
This works:
```julia
using GLMakie
using InteractiveViz
display(GLMakie.Screen(), ilines(sin, 0, 100).fap)
display(GLMakie.Screen(), ilines(cos, 0, 100).fap)
```

So all that remains is to clean up the API to avoid the `.fap`

**Comment by mchitre** [comment]
Fixed. This now works:
```julia
using GLMakie
using InteractiveViz
display(GLMakie.Screen(), ilines(sin, 0, 100))
display(GLMakie.Screen(), ilines(cos, 0, 100))
```
