### ISSUE TITLE
Add support for `heatmap!` to support opacity / blending

### ISSUE THREAD

**Issue by mchitre** [org-arl/InteractiveViz.jl#22]
See discussion in #21.

**Comment by ConnectedSystems** [comment]
I have a tentative working example for this.

See the changes here: 
https://github.com/ConnectedSystems/InteractiveViz.jl/blob/ebb35059183c6dfdd3d15ab168accca9f2f74c78/src/interface.jl#L153

I'm just leveraging Makie's existing heatmap arguments, but not sure if I'm missing/ignorant of some nuance regarding blending and opacity.


```julia
f = iheatmap(ones(10_000, 10_000))
```

![image](https://github.com/org-arl/InteractiveViz.jl/assets/4075136/1c1145fd-955e-47fe-9434-2ba8b8f62137)


```julia
iheatmap!(f, rand(10_000, 10_000); alpha=0.1)
```

Zoomed in view:

![image](https://github.com/org-arl/InteractiveViz.jl/assets/4075136/78123796-4582-48aa-a072-f8a827457a26)

**Comment by mchitre** [comment]
Thanks @ConnectedSystems. If it meets your needs, it is a good start.

It would be nice to support all the different variants of inputs, just like `iheatmap` to be complete. Also, would appreciate if you move the additions to just after the `iheatmap` definitions, so they are easily found together.

**Comment by ConnectedSystems** [comment]
> Also, would appreciate if you move the additions to just after the iheatmap definitions, so they are easily found together.

Actually, I had a question for you. Would you mind if all the method definitions are moved below the struct/type definitions?

Doing so would allow the argument types to be annotated.

For example, the current tentative implementation defines the two:

```julia
iheatmap!(g::Axis, z::AbstractMatrix; kwargs...)
iheatmap!(g::FigureAxisPlotEx, z::AbstractMatrix; kwargs...)
```

Which allows:

```julia
# Create example heatmap
g = iheatmap(rand(5_000, 5_000))

# Add to figure above
iheatmap!(g, rand(5_000, 5_000))

# Support axis objects as well, which seems to be current expected object?
iheatmap!(g.axis, rand(5_000, 5_000))
```

The above is only possible with the argument `g` annotated, and annotation is only possible if the methods are defined after the type definitions.

> It would be nice to support all the different variants of inputs, just like iheatmap to be complete.

Sure will do

**Comment by ConnectedSystems** [comment]
A small update - I've added a slight delay to interactions and it resolves most of the issues I had around fast panning and zooming/scrolling I mentioned in #23.


https://github.com/org-arl/InteractiveViz.jl/assets/4075136/9550dcb1-2e91-40b1-bd20-73e954cea4f3

**Comment by mchitre** [comment]
@ConnectedSystems, no problem moving all below.

**Comment by marianoarnaiz** [comment]
> @ConnectedSystems, no problem moving all below.

Could you let me know how to pass another pool option to iheatmap

**Comment by ConnectedSystems** [comment]
@marianoarnaiz Sorry I'm not sure I understand. What do you mean by pool option?
