### ISSUE TITLE
iheatmap!

### ISSUE THREAD

**Issue by marianoarnaiz** [org-arl/InteractiveViz.jl#24]
Hi all.
I was looking at the code and iheatmap! is missing. It is useful to add to axis in makie.
Any chance to add it?
https://github.com/org-arl/InteractiveViz.jl/blob/52ce0ffb5c2642289239b3e68f715d25dad162f0/src/interface.jl#L32
thanks a lot!

**Comment by ConnectedSystems** [comment]
Hi @marianoarnaiz see https://github.com/org-arl/InteractiveViz.jl/pull/25
