### ISSUE TITLE
Hope to support makie "0.21" version, each update is limited by InteractiveViz

### ISSUE THREAD

**Issue by 13299118606** [org-arl/InteractiveViz.jl#27]
Hope to support makie "0.21" version, each update is limited by InteractiveViz

[compat]
julia = "1.6"
FillArrays = "1.0"
Makie = "0.19, 0.20,0.21"

**Comment by mchitre** [comment]
Updated compat on `master`. Pending merging of https://github.com/JuliaRegistries/General/pull/110060 for release.

**Comment by 13299118606** [comment]
Thank you very much, the latest package can be downloaded.
