### ISSUE TITLE
Enable numeric keypad shortcuts by default

### ISSUE THREAD

**Issue by Orcomp** [org-arl/InteractiveViz.jl#6]
Thanks for putting this package together. It is nice once I was able to get it running.

It took me a while to figure this out but I had to use `using InteractiveViz, Makie` to get the plots to show up. (i.e. notice the "using Makie")

The Mandlebrot example is actually using the "Julia" set.

The shortcut keys do not work with the num pad keys. You need to use -/+ and 0 on the main keyboard

**Comment by mchitre** [comment]
Thanks for the feedback.

1. You should not require a `using Makie` for the plots to show up (I just reconfirmed this with a fresh install). If you do, there is some problem, and a detailed error message may be useful to debug.

2. Copy'n'paste error in updating the example. Thanks for spotting it. Fixed.

3. For the shortcut keys, you can customize them to your liking (see #1).  I will add in the numeric keypad versions as defaults in the next release (renamed issue to reflect this).

**Comment by Orcomp** [comment]
Thanks for the reply.

1. You are right. It looks like Makie is not needed anymore. Not sure what I was doing before. (I am new to Julia and am trying a lot of different things, so please ignore.)

2. Thanks.

3. Ok great. Will have a look

**Comment by mchitre** [comment]
No longer relevant since key bindings are now handled by GLMakie directly.
