### ISSUE TITLE
Depend on AbstractPlotting

### ISSUE THREAD

**Issue by SimonDanisch** [org-arl/InteractiveViz.jl#7]
First of all, nice package!! :)
Just wanted to drop in, and say, that you should rather depend on AbstractPlotting, instead of Makie:
https://github.com/org-arl/InteractiveViz.jl/blob/80fd2a5216c9ebd454c39bb54c3284fcba233dd7/Project.toml#L8
`using Makie` is identical to `using AbstractPlotting, GLMakie`. But if you just depend on AbstractPlotting, your users can easily switch out backends, and e.g. display those plots in the web or save it to a pdf with CairoMakie ;) 
If you want to have GLMakie as a default backend readily available for your user, depending on Makie.jl is fine, since it's still possible for the user to switch backends ;) They just always need to compile GLMakie as well, even when not using it!

**Comment by mchitre** [comment]
Thanks for the feedback. Will update.

**Comment by mchitre** [comment]
Done
