### ISSUE TITLE
Wrong example for Mandlebrot

### ISSUE THREAD

**Issue by vapidbabble** [org-arl/InteractiveViz.jl#9]
Example for Mandlebrot at 
https://juliahub.com/docs/InteractiveViz/AYpiK/0.1.2/
shows the Julia set.

Next, let us visualize the famous Mandelbrot set:

julia> using InteractiveViz.demo
julia> iheatmap(julia, -2, 2, -1.75, 1.75; overlay=true, axescolor=:white, colormap=:magma);

Should be
iheatmap(mandelbrot, -2, 0.66, -1, 1; overlay=true, axescolor=:white, cursor=true); 

per the github page.

**Comment by mchitre** [comment]
Thanks. This is already fixed on the master branch, and will be picked up by JuliaHub once the next release is cut. Soon.

**Comment by vapidbabble** [comment]
Okay. Thank you. It’s a fantastic package BTW.

-jmwise

**Comment by mchitre** [comment]
Thanks @vapidbabble
